<?php
declare(strict_types=1);

/**
 * POST /api/chapters/generate_structured.php
 *
 * Saves pre-generated content for a specific chapter to the database.
 * The AI generation is expected to be handled by the client.
 *
 * JSON Body:
 * {
 *   "chapterId": 456,
 *   "content": "The full markdown content generated by the client..."
 * }
 *
 * Response 200 (OK):
 * {
 *   "ok": true,
 *   "message": "Chapter content saved successfully.",
 *   "chapterId": 456
 * }
 */

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../lib/auth.php';
require_once __DIR__ . '/../lib/tokens.php';

// --- Helpers ---

function json_out(int $code, array $data): void {
    http_response_code($code);
    echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    exit;
}

function body_json(): array {
    $raw = file_get_contents('php://input');
    $data = json_decode($raw, true);
    return is_array($data) ? $data : [];
}

// --- Endpoint Logic ---

try {
    // 1. Authenticate user
    $claims = require_auth();
    $userId = (int)($claims['sub'] ?? 0);
    if ($userId <= 0) {
        json_out(401, ['ok' => false, 'error' => 'invalid_token_subject']);
    }

    // 2. Get and validate input
    $input = body_json();
    $chapterId = (int)($input['chapterId'] ?? 0);
    $content = trim((string)($input['content'] ?? ''));

    if ($chapterId <= 0 || $content === '') {
        json_out(422, ['ok' => false, 'error' => 'A valid chapterId and non-empty content are required.']);
    }

    $pdo = get_pdo();

    // 3. Verify that the chapter exists and belongs to the authenticated user
    $stmt = $pdo->prepare(
        'SELECT c.id FROM chapters c
         JOIN books b ON c.book_id = b.id
         WHERE c.id = :cid AND b.user_id = :uid
         LIMIT 1'
    );
    $stmt->execute([':cid' => $chapterId, ':uid' => $userId]);

    if (!$stmt->fetch()) {
        json_out(404, ['ok' => false, 'error' => 'Chapter not found or you do not have permission.']);
    }

    // 4. Save content to the database
    $updateStmt = $pdo->prepare(
        'UPDATE chapters SET generated_content = :content, status = "ready", updated_at = NOW() WHERE id = :cid'
    );
    $updateStmt->execute([':content' => $content, ':cid' => $chapterId]);

    if ($updateStmt->rowCount() === 0) {
        // This can happen if the content was identical to what was already in the DB,
        // but we'll treat it as a success since the desired state is achieved.
    }

    // 5. Return success response
    json_out(200, [
        'ok' => true,
        'message' => 'Chapter content saved successfully.',
        'chapterId' => $chapterId,
    ]);

} catch (Throwable $e) {
    $msg = (defined('DEBUG') && DEBUG) ? ($e->getMessage() . ' @ ' . basename($e->getFile()) . ':' . $e->getLine()) : 'server_error';
    json_out(500, ['ok' => false, 'error' => $msg]);
}